version: "3.9"

services:
  backend:
    build:
      context: ./.
      target: backend
    volumes:
      # bind mounts
      - ./data/input:/volumes/input:ro
      - ./data/param_config:/volumes/param_config:ro
      # named volume
      - output:/volumes/output

volumes:
  output:
