version: "3.9"
services:
  biotaphy:
    image: conda/miniconda3:latest
    command: ["clean_occurrences",
              "--species_key", "species_name",
              "--x_key", "x",
              "--y_key", "y",
              "--report_filename", "/output/cleaning_report.json",
              "--log_output", "True",
              "/input/heuchera.csv",
              "/output/clean_heuchera.csv",
              "/input/wrangler_conf.json"]
    build:
      context: ./.
      target: biotaphy
    ports:
      - 3000:3000
    working_dir: /tutorials
#   use bind-mounts
    volumes:
      - "./:/tutorials"
      - "./data/input:/input:ro"
      - "./data/output:/output"
      - "./data/log:/log"
