version: "3.9"

services:
  backend:
    build:
      context: ./.
      target: backend
    volumes:
      # bind mounts
      - ./data/input:/volumes/data/input:ro
      - ./data/config:/volumes/data/config:ro
      # named volume
      - output:/volumes/output

volumes:
  output:
