version: "3.9"
services:
  backend:
    build:
      context: ./.
      target: backend
    command: [pip, list]
    ports:
      - 3000:3000
#   use bind-mounts
    volumes:
      - "./data/output:/home/biotaphy/data/output"
      - "./data/log:/home/biotaphy/data/log"

