version: "3.9"
services:
  backend:
    build:
      context: ./.
      target: backend
    command: [pip, list]
    ports:
      - 3000:3000
#   use bind-mounts
    volumes:
      - "./:/tutorials"
      - "./data/input:/input:ro"
      - "./data/output:/output"
      - "./data/log:/log"
