version: "3.9"

services:
  backend:
    build:
      context: ./.
      target: backend
    ports:
      - 3000:3000
    # bind-mount output directories
    volumes:
#      - "./data:/biotaphy_data"
      - "./data/output:/biotaphy_data/output"
      - "./data/log:/biotaphy_data/log"
