version: "3.9"

services:
  backend:
    build:
      context: ./.
      target: backend
#    command: [ $command, "--config_file", $config_file ]
    ports:
      - 3000:3000
    # bind-mount output directories
    volumes:
      # Map output directories to retain modifications on host
      - "./data/output:/biotaphy_data/output"
      - "./data/log:/biotaphy_data/log"
